### ISSUE TITLE
Unable to play live stream

### ISSUE THREAD

**Issue by ronluna** [elad-bar/ha-shinobi#45]
Wondering if it's just me going crazy or this never worked. I was under the impression that live stream was possible within Home assistant. Currently when a camera is being access through home assistant the overlay come up but it's is not the regular live stream is shown when accessing an rtso stream. instead the overlay pops with a refresh rate of 1 image per second... Not sure if during a home assistant upgrade the live stream broke (as I believe it was working with the live stream before) or maybe something change in the latest shinobi upgrade? 

any ideas?

**Comment by elad-bar** [comment]
Are you using the latest release of component?
Do you have stream component define?

Thanks

**Comment by ronluna** [comment]
I believe I'm using the latesst component version

<img width="337" alt="image" src="https://user-images.githubusercontent.com/9822111/223292772-abcca3f8-6da1-4807-ae8e-4e691afc1241.png">

Stream component defined? Well. the Shinobi Integration automagically pull all the cameras from Shinobi and make it available to use in HA. I'm almost certain that a few days ago the cameras thumbnails were refreshing every 10 seconds and when clicking on it the popup will ask to hit the play button to start the live streaming. Now it does not starts the live streaming but refreshing every second. or am I crazy ? lol

**Comment by elad-bar** [comment]
You are on the latest version indeed, I had the same problem with previous version that is the reason I released new one, not sure why it's not working for you, can you pls uninstall, restart HA, make sure the folder is empty (if not, delete it), restart again and then reinstall?
I'm suspecting the component is cached somehow

**Comment by ronluna** [comment]
Just tried your suggestion but same results. no live streaming... any other ideas?

**Comment by elad-bar** [comment]
will need logs, diagnostic details and screenshot of the entity details from developer tab 

in each of the files pls make sure to delete sensitive data

**Comment by ronluna** [comment]
Perhaps it could be easier to share access to the system? is there a more private way to reach you ?

**Comment by elad-bar** [comment]
relevant data is crucial for me to assist you with the issue you have opened, 
I asked to hide senstive data because I do not want you to share it with all, but an example of the issue you are presenting will be useful for both solving the problem and for others if they encouter the same issue.

Senestive information from the diagnostic file (of specific monitor) are:
TOKEN, GROUP ID / ke, host, port, username

as for the snapshot:
![image](https://user-images.githubusercontent.com/3207137/225252884-088bbd45-79e3-4ef8-8504-61178d6d973d.png)

if you would like to contact me more privatly, feel free to contact me over HA forum

**Comment by elad-bar** [comment]
Fillowing private conversation with @ronluna, issue solved in v2.0.34 and not v2.0.33, if you are experiencing that issue, pls upgrade to latest

Thanks
